spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

webServices:
  randomUser:
    url: ${RANDOM_USER_URL:https://randomuser.me/api/}
    keys:
      public: ${RANDOM_USER_PUBLIC_KEY:""}
      private: ${RANDOM_USER_PRIVATE_KEY:""}
  marvel:
    url: ${MARVEL_URL:https://gateway.marvel.com:443/v1/}
    keys:
      public: ${MARVEL_PUBLIC_KEY:ce0e26bf2f195432fdf314e0a488dcc2}
      private: ${MARVEL_PRIVATE_KEY:5e4773062d1847c4ee47b47dbb45127d9ad65ab3}
      hash: ${MARVEL_HASH_KEY:eabfb5c9c60b318884079326e1caa4e1}
      ts: ${MARVEL_TS:1}